#!/bin/bash
# KACA Streamlit Dashboard Launcher
# Generated by Kearney AI Coding Assistant

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

PORT=${1:-8501}

echo "+==============================================+"
echo "|  KACA Dashboard Launcher                     |"
echo "+==============================================+"

# Kill existing processes on port
echo "-> Checking port $PORT..."
lsof -ti:$PORT | xargs kill -9 2>/dev/null || true
sleep 1

# Install dependencies
if [ -f "requirements.txt" ]; then
    echo "-> Installing dependencies..."
    pip install -r requirements.txt -q
fi

# Verify imports
echo "-> Verifying imports..."
python3 -c "import streamlit, pandas, plotly" || {
    echo "[x] Missing dependencies. Run: pip install -r requirements.txt"
    exit 1
}

# Launch
echo "-> Launching dashboard on port $PORT..."
echo ""
streamlit run app.py --server.port=$PORT --server.headless=true &

# Wait and verify
sleep 3
if curl -s -o /dev/null -w "%{http_code}" "http://localhost:$PORT" | grep -q "200"; then
    echo "[ok] Dashboard running at http://localhost:$PORT"
    echo ""
    echo "Commands:"
    echo "  Open:  open http://localhost:$PORT"
    echo "  Stop:  lsof -ti:$PORT | xargs kill"
else
    echo "[x] Failed to start dashboard"
    exit 1
fi
